<template>
	<div class="row">
		<div class="col-sm-4">
			<rs-cascader :cascader="cascadeDate"></rs-cascader>
		</div>
	</div>
</template>
<script>
	import RsCascader from '../form/RsCascader.vue'
	export default{
		data(){
			return{
				cascadeDate:{
					label:'城市',
					labelType:'head',
					secondLabel:'(随便填)',
					important:true,
					default:"请选择所在位置",
					join:" / ",
					disable:false,
					option:[{
						value:'china',
						label:'中国',
						children:[{
							value:'liaoning',
							label:'辽宁',
							children:[{
								value:'shenyang',
								label:'沈阳',
								children:[{
									value:'shenhe',
									label:'沈河',
									children:[{
										value:'shandongmiao',
										label:'山东庙街道',
										children:[{
											value:'railway',
											label:'铁路小区'
										}]
									}]
								}]
							},
							{
								value:'dalian',
								label:'大连'
							},
							{
								value:'anshan',
								label:'鞍山'
							},
							{
								value:'fushun',
								label:'抚顺'
							},
							{
								value:'benxi',
								label:'本溪'
							}]
						},
						{
							value:'zhejiang',
							label:'浙江',
							children:[{
								value:'hangzhou',
								label:'杭州'
							},
							{
								value:'ningbo',
								label:'宁波'
							},
							{
								value:'jinhua',
								label:'金华'
							},
							{
								value:'quzhou',
								label:'衢州',
								disable:true
							}]
						},
						{
							value:'guangdong',
							label:'广东',
							children:[{
								value:'guangzhou',
								label:'广州'
							},
							{
								value:'shenzhen',
								label:'深圳'
							},
							{
								value:'zhuhai',
								label:'珠海'
							},
							{
								value:'huizhou',
								label:'惠州'
							}]
						}]
					},
					{
						value:'usa',
						label:'美国',
						children:[{
							value:'California',
							label:'加利福尼亚',
							children:[{
								value:'Los Angeles',
								label:'洛杉矶'
							},
							{
								value:'Orange',
								label:'奥兰治'
							},
							{
								value:'Nevada',
								label:'内华达'
							},
							{
								value:'Madera',
								label:'马德拉'
							},
							{
								value:'San Diego',
								label:'圣迭戈'
							}]
						},
						{
							value:'Florida',
							label:'佛罗里达',
							children:[{
								value:'Miami',
								label:'迈阿密'
							},
							{
								value:'Baker',
								label:'贝克'
							},
							{
								value:'Hillsborough',
								label:'希尔斯伯勒'
							},
							{
								value:'Saint Lucie',
								label:'圣卢西亚'
							}]
						}]
					}]
				}
			}
		},
		components:{
			RsCascader
		}
	}
</script>